Algoritmo "semnome"
// Disciplina   : [UC4 - Lógica de Programação]
// Professor   : Richard Brosler 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/05/2022
Var
// Seção de Declarações das variáveis 
i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 para i de 100 ate 1 passo -1 faca
  escreval(i, " ")
fimpara
Fimalgoritmo