Algoritmo "semnome"
// Disciplina   : [UC4 - Lógica de Programação]
// Professor   : Richard Brosler 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/05/2022
Var
// Seção de Declarações das variáveis 
i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Usando o enquanto")
 i <- 1
  enquanto i <=100 faca
   escreva (i, " ")
    i <- i + 1
fimenquanto

Fimalgoritmo